web.url=https://dev-cinescope.t-qa.ru
auth.api.url=https://auth.dev-cinescope.t-qa.ru
movies.api.url=https://api.dev-cinescope.t-qa.ru
selenoid.url=
database.jdbc.url=jdbc:postgresql://localhost:15432/aqa
database.username=aqa
kafka.bootstrap.servers=localhost:19092
vault.address=http://localhost:18200
vault.secret.path=secret/data/java-aqa/dev
