web.url=
auth.api.url=
movies.api.url=
selenoid.url=
database.jdbc.url=jdbc:postgresql://localhost:25432/aqa
database.username=aqa
kafka.bootstrap.servers=localhost:29092
vault.address=http://localhost:28200
vault.secret.path=secret/data/java-aqa/uat
