name: java-aqa-cicd-example

services:
  selenoid:
    build:
      context: .
    image: java-aqa-selenoid:1.11.3
    command:
      - -conf
      - /etc/selenoid/browsers.json
      - -container-network
      - tqa-selenoid
      - -limit
      - "4"
      - -timeout
      - 2m
      - -log-output-dir
      - /opt/selenoid/logs
    ports:
      - "${SELENOID_PORT:-4444}:4444"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - selenoid-logs:/opt/selenoid/logs
    networks:
      - selenoid

  selenoid-ui:
    image: aerokube/selenoid-ui:1.10.11
    command:
      - --selenoid-uri
      - http://selenoid:4444
    depends_on:
      - selenoid
    ports:
      - "${SELENOID_UI_PORT:-8090}:8080"
    networks:
      - selenoid

networks:
  selenoid:
    name: tqa-selenoid

volumes:
  selenoid-logs:
